spring:
  application:
    name: cricket-api-gateway
  cloud:
    gateway:
      routes:
        - id: insert-match-data
          uri: http://localhost:8081
          predicates:
            - Path=/api/matches/upload

        - id: get-matches-by-player
          uri: http://localhost:8081
          predicates:
            - Path=/api/matches/player/**

        - id: get-cumulative-score
          uri: http://localhost:8081
          predicates:
            - Path=/api/matches/cumulativeScore/**

        - id: get-scores-by-date
          uri: http://localhost:8081
          predicates:
            - Path=/api/matches/date/**

        - id: get-top-batsmen
          uri: http://localhost:8081
          predicates:
            - Path=/api/matches/batsmen/top

server:
  port: 9000  # API Gateway will run on port 9000
